version: 2
jobs:
  build:
    working_directory: ~/cucumber/cucumber-ruby-tcl
    parallelism: 1
    shell: /bin/bash --login

    environment:
      C_INCLUDE_PATH: /usr/include/tcl8.5/

    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
    steps:
    - checkout
    - run:
        working_directory: ~/cucumber/cucumber-ruby-tcl
        command: sudo apt-get install tcl8.5-dev
    - restore_cache:
        keys:
        # This branch if available
        - v1-dep-{{ .Branch }}-
        # Default branch if not
        - v1-dep-master-
        # Any branch if there are none on the default branch - this should be unnecessary if you have your default branch configured correctly
        - v1-dep-
    - run: 'bundle check --path=vendor/bundle || bundle install --path=vendor/bundle --jobs=4 --retry=3 '
    # Save dependency cache
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - vendor/bundle
        - ~/.bundle
    - run: bundle exec rake

